### ISSUE TITLE
AttributeError: type object 'onnxparser' has no attribute 'create_onnxconfig'

### ISSUE THREAD

**Issue by abi98213** [modricwang/Pytorch-Model-to-TensorRT#1]
First of all, I had to import tensorrt as 
**import tensorrt.legacy as trt**
Becuase if I do 
**import tensorrt.parsers**
it says no tensorrt has not attribute parser.
But when I run main.py, afer some time it give the error 
"AttributeError: type object 'onnxparser' has no attribute 'create_onnxconfig'"
Please tell me, how can I solve this issue.

**Comment by modricwang** [comment]
Hello, please tell me your python version, TensorRT version and PyTorch version so that I can reproduce it.

**Comment by yanxp** [comment]
Hello, what is the data and model? Thanks!

**Comment by shiyi001** [comment]
We supply data and model in our new version. Please check [README.md](https://github.com/modricwang/Pytorch-Model-to-TensorRT).

**Comment by yanxp** [comment]
@shiyi001 I meet the problem:Segmentation fault when run to the line:engine = builder.build_cuda_engine(trt_network). Would you know why, thanks.

**Comment by shiyi001** [comment]
> @shiyi001 I meet the problem:Segmentation fault. Would you know why, thanks.

Can you supply your env and complete error message? 
- python version
- pytorch version
- cuda version
- cudnn version
- complete error mesage

I can not locate the problem without that information.

**Comment by yanxp** [comment]
@shiyi001 python=2.7,cuda=8.0,cudnn=7,pytorch=0.4.0,tensorrt=4.0.1.6

**Comment by modricwang** [comment]
@yanxp Please try CUDA=9.0 since you are using cuDNN=7

**Comment by shiyi001** [comment]
> @shiyi001 python=2.7,cuda=8.0,cudnn=7,pytorch=0.4.0,tensorrt=4.0.1.6

In fact，I came up with `Segmentation fault` like you as I used cudnn=7.0. The error disappear when I change cuda and cudnn to cuda==9.0 and cudnn==7.3.1 .

**Comment by yanxp** [comment]
@shiyi001 @modricwang Thanks. I'll try it.

**Comment by modricwang** [comment]
Close for now, waiting for mabdullahrafique's further response.

**Comment by Tian14267** [comment]
I get same problem ,and my version is : python==3.5, cuda==10.1, cudnn==7.6, tensorrt==5.1. How should I solve this problem? @modricwang
